#ifndef Demo_codeObfuscation_h
#define Demo_codeObfuscation_h
//confuse string at Mon Jan 29 18:10:14 CST 2018
#define unbandCard dlyxknTKXAmTGSbS
#define getAuthTools TzeaRwXpPqMUYCnN
#define getBankType mZGctHGhBiiBolBh
#define changeIconImage fvZwTLOLJEnqrUoo
#define openFastPayTWO sSwdWqXSEiMfYVnQ
#define openFastPay FMwpkRAYJFnqYQLp
#define fee uRzsZqeJbYILUgju
#define createChildViewControllers wafQPYRuoKrphciI
#define setNavigationTheme daveaQBKwVCMoItO
#define commitChange YiOTXvCaBUDLPrWX
#define initMinletsBtn lRDpgpWRvWBxdMtj
#define loadData YJXGvfzVuLDLvpnH
#define undergroundLogin PxjGYQDcIcTCYHMa
#define ownPayTools lKNsmIzusYKSgtur
#define setData CmdcirXehnKgVzNI
#define exitApplication AnxmFfGlVEYSAavI
#define jsonToString sOXpXJlTOEkmvppn
#define jsonToDictionary fgQulwxfySlGIHXd
#define jsonToArray gGdNHnQoDQtVixoM
#define jsonStringToDictionary KGLJmFxiuaYJxShV
#define dictionaryToJson unZLxGyagXKnlbWX
#define jsonStringToArray wOaMohGxrttCUuSL
#define arrayToJSON yzElQYohSHyPwrRN
#define passwd JcVupFbxBtLktWTu
#define limitInfo iNjqkrySfxmOMsla
#define limit fPuCFZHJkeLKcGQd
#define load SIDGnGhwtVmQMakU
#define settingNavigationBar KCCcpYdFgfclujcG
#define cusWebView bzTyKEUyJebfpjyv
#define cusWebViewDidStartLoad BoZxzRnXmZSyCRUO
#define buttonActionToDoSomething joLFQAajympCwtBO
#define addView zZengDLyDxrwgkpZ
#define SandMajletIndex yAWQgcOuTbnHZcxa
#define paramString BXUnyGNgoBPcqmyI
#define payPwd pSBYPosWzWHPyiDZ
#define defaultPay DaKhwNBWmWJhSJrX
#define TNOrder XxLPbzoXDicgTdxW
#define initPayMode fknhUziKYWLXZOdZ
#define readAuthCode yfoEVAEQFYmXGvbM
#define refreshAuthCode tzDEcEyFtTvEuhPo
#define oneCodeContentFotmat CEHuwKAGdyzYANnv
#define oneCodeTapShowBigView HstZvwPJjYaGcQEt
#define twoCodeImageScaleBigAnimation qDkxYbhCiyboHDwb
#define buttonAction yWkmqlZeGceOOytZ
#define changePwdShowState nFiCoxvxCvKMQFLL
#define listenNotifier XbmBdAvvSaKExbRB
#define textFiledEditChanged urtvKoXNOXhrmFPv
#define changeBtnBackGround zfCHTtEumawvjydT
#define allInputFields ClhGaGHzoZTRHKua
#define textFieldDidBeginEditing znfXCQmgBJQkIAan
#define textFieldShouldReturn DsLdeUdwDjUwEGOW
#define setNextResponder HsobrZfTtpFLixmb
#define setInputResponderChain XykwdoBuhUxXpiol
#define dismissKeyboard JgZwhFatjVPHRzYB
#define addAuthToolsView vmgvIbaLfefOFnZg
#define shortMsgCodeCountDown XgxHALlhfWUGOerk
#define refreshTime GrjzdfbSKAgdeapR
#define shortMsg QVFczXSIaNmukItZ
#define verificationInput efcJALnGkfDtAEeE
#define submit WarYrGeFdzRvoKXS
#endif
