#ifndef Demo_codeObfuscation_h
#define Demo_codeObfuscation_h
//confuse string at Thu Jan  4 16:30:03 CST 2018
#define unbandCard yGbqRkFLsVvdYmSf
#define getAuthTools PWevQVbpnaHaqhpv
#define getBankType vkPGViCgODUMSpmP
#define changeIconImage XnCnkMXQbPjlLxXg
#define openFastPayTWO ALwAIhOlreTyNTAH
#define openFastPay GznQNbGsaNYCjlXM
#define fee mMtWehsQtZQviQCr
#define createChildViewControllers RrTsDYLeEQtAylYy
#define setNavigationTheme PTjFTJAndodgSKpX
#define commitChange inzzuPvrQTJqLxby
#define initMinletsBtn JvdsULjmbJNjVWnf
#define loadData yDgdzKprfseIJbII
#define undergroundLogin TNCgYkgqKCJvKyMQ
#define ownPayTools ayeAjzBqOpJMoGwL
#define setData XweFFUtKcGwVObet
#define exitApplication CuSeGXGebIvqvpKa
#define jsonToString QfUiCBNxtLNNdIlI
#define jsonToDictionary qdAaWWDEXOaVJBQy
#define jsonToArray ZvzbCKllwYrVXXps
#define jsonStringToDictionary uQlrkQZWiKkSdsPj
#define dictionaryToJson noctRiGvtgcymUdf
#define jsonStringToArray rNMsUYwdmnZNoiUJ
#define arrayToJSON xonkqnTTNyfJACuJ
#define passwd YdbqTepFUKWMsnHp
#define limitInfo boDCdmIWYVtGwsnB
#define limit rwQudCcObzRxArox
#define load sOIDMNxeJPeVVnmz
#define settingNavigationBar XfTpoxCYRxffKSDA
#define cusWebView tjYtclBLFwwdWCTD
#define cusWebViewDidStartLoad BnoLRdeAdEVesjdO
#define buttonActionToDoSomething eMwQqlCOosoJcMWI
#define addView EzRMywjRJCfoNSkC
#define SandMajletIndex oFqEIVhkqOgoTsfH
#define paramString WOBcWOQfQiWMUoos
#define payPwd VvDTBnzBLEiyyPkW
#define defaultPay bvXidtSYiWcPJVVG
#define TNOrder wnPSXloFhFBofYuL
#define initPayMode MMoIgorvqNPFVsKf
#define readAuthCode FSQtuLVcUvHWYwxf
#define refreshAuthCode feOmLnbnQoYJOrug
#define oneCodeContentFotmat lrrsurZtzdmiGVNy
#define oneCodeTapShowBigView dvyrUPrcycDVhoLl
#define twoCodeImageScaleBigAnimation TApmKCVKzQfmCoWJ
#define buttonAction irCbzOFyaRXPoIgG
#define changePwdShowState mLnjXlTXPuAkfcDr
#define listenNotifier lDWybIxYMRmAcSLa
#define textFiledEditChanged mKZwJJaHGVsRCZMx
#define changeBtnBackGround ZJiOKxctffGDDAcc
#define allInputFields bCjnpEDHwXucJjTr
#define textFieldDidBeginEditing HVICmcOyKFvmNmOx
#define textFieldShouldReturn XvJXKUdCVAgEngYt
#define setNextResponder PiDHsJkhzPtAIRrC
#define setInputResponderChain akHRFklgMRwzRNsW
#define dismissKeyboard WxDPKBELjJcOQAJe
#define addAuthToolsView YjYxBWNYPhgcPYxP
#define shortMsgCodeCountDown hGBqoedPIUDzLUsK
#define refreshTime uMxcuCvdGAXRchWE
#define shortMsg GWgUcEccGWhSQEKd
#define verificationInput MJCPkKnrSUBvHuKQ
#define submit exHNinuLPRmrMBPc
#endif
