#ifndef Demo_codeObfuscation_h
#define Demo_codeObfuscation_h
//confuse string at Mon Dec 25 22:50:37 CST 2017
#define unbandCard vScfaHmVvZopoBwp
#define getAuthTools zBxXkmmFjrpwowxW
#define getBankType bBxwDDwfkPpdBQQA
#define changeIconImage NAZVlCjzWXSdKLAl
#define openFastPayTWO uLIezdhqUdVdoGfp
#define openFastPay cuYqSlZWMrufRomp
#define fee YbEfsmPWpUOpLKns
#define createChildViewControllers GoWpXZGIwgboSkFI
#define setNavigationTheme xwRSvPDDFKwCFRuy
#define commitChange ptYrOtxtYybPMDFm
#define initMinletsBtn MtRvvarkkakEBAnM
#define loadData hDeqTHwzQvDlSbSo
#define undergroundLogin iDszcJrPGHYPNPUs
#define ownPayTools plYLlMxTpzOpLvQI
#define setData sMtdKYNOuXBTWyUA
#define exitApplication zqtIkJLZyxkJxwSy
#define jsonToString LDhmjOgZPTeOgYjr
#define jsonToDictionary GuycgQXNtOmKvUdQ
#define jsonToArray EGVjXgcsyRqTAAdE
#define jsonStringToDictionary YXkEHRcdjJhaiCvm
#define dictionaryToJson GNaYpFggiqqUjoLC
#define jsonStringToArray huNSWdXznmAXEEwA
#define arrayToJSON CpBfYzRwmUokIVFc
#define passwd zwDbJvijlshvmbrj
#define limitInfo MUfeguqWnawsIOwn
#define limit FgtsCRBaHSraqZon
#define load jHumreQGUWIJYbyo
#define settingNavigationBar cbHnMEzfcTvHXuGP
#define cusWebView CTMcqvDVoLVDWRHr
#define cusWebViewDidStartLoad BGOWlXEsWUDepGaP
#define buttonActionToDoSomething BSaIvhwFTUKrIlRC
#define addView GYsiSjPtqjeDAAti
#define SandMajletIndex kUXiOIPvozuSEuMx
#define paramString NbuZQVVOMQGSnIwh
#define payPwd tXoDRJAewIQXatRU
#define defaultPay YzIXnNjllJMRsBZP
#define TNOrder PQxKzPegBpADkrbF
#define initPayMode yDkAczUHKmvSpAVI
#define readAuthCode zvGtamNntIWTSLzj
#define refreshAuthCode aQgtsSkPTUWWrACV
#define oneCodeContentFotmat fiiQQqKLnzopevJU
#define oneCodeTapShowBigView tRrOOBCmGpGnzhAb
#define twoCodeImageScaleBigAnimation yEqtIdceMKNEPwyu
#define buttonAction kivYWyXZyXVUMLut
#define changePwdShowState GdEfEoZwpBbZZwQD
#define listenNotifier BmTbaAyCUVQeMlEz
#define textFiledEditChanged LvlzghqBMwCkVwfU
#define changeBtnBackGround pOQWZoSZwZsaqiBB
#define allInputFields gnpJMxxfQWzNcBaV
#define textFieldDidBeginEditing KlYdWNdqygngwzOS
#define textFieldShouldReturn uxvjibmoUOJIoMjG
#define setNextResponder MotNtBdZtOmuXQvD
#define setInputResponderChain QCNoSkHtbVRJnzwo
#define dismissKeyboard OdqMhhMtOHdedpBB
#define addAuthToolsView iPSSKqxdjPqnFKYO
#define shortMsgCodeCountDown jTkCyCQWlHjTBWmP
#define refreshTime xlXGhOeDLgsUVAMh
#define shortMsg yguBaFORhzBQfGaH
#define verificationInput CjHETjxMUZBauvZe
#define submit OEyPVIWNgCKgKdEi
#endif
