#ifndef Demo_codeObfuscation_h
#define Demo_codeObfuscation_h
//confuse string at Fri Nov 17 14:50:20 CST 2017
#define unbandCard oWaTWevOkYkLpomY
#define getAuthTools NpRuUmxdtAerCsBy
#define getBankType leANWqxndvdzlSMh
#define changeIconImage xuexefiOyigMXqlV
#define openFastPayTWO YxQdISjvaVXnwxQB
#define openFastPay ywVtwmwTwJhHrIXS
#define fee ZWCMVnbriMddVjgx
#define createChildViewControllers FEWwAFgPgMqniGVm
#define setNavigationTheme eUPNwNtfHjkKJKwl
#define commitChange WpovZyiQsIWoLCOn
#define initMinletsBtn rCzMhzIRtzRixDkb
#define loadData bSRXsQFFmCpHCBhc
#define undergroundLogin eVDUECcdbVzAItwx
#define ownPayTools MKYsWgIEbYvITdBJ
#define setData jnxdhhYMdvrffTzp
#define exitApplication XLDjtqeoteYtVxcR
#define jsonToString sNDePtWnNYzxVpQN
#define jsonToDictionary oantPSvQlTgHzfVy
#define jsonToArray EmKPiiRaVgnBJIyb
#define jsonStringToDictionary hxCsInSBCsdGhsgO
#define dictionaryToJson tokANirkCrgqxRhR
#define jsonStringToArray yLRsOhNHHIUXvvQp
#define arrayToJSON pscsZcwwiuceqfZD
#define passwd wJyAFGRjFcWUhvxX
#define limitInfo sbbQaBfkNfzBgNVq
#define limit sWRLtnyuvHEPPwhO
#define load vZKCwMzPftFBCbMo
#define settingNavigationBar InJOKcezgRSGyDBw
#define cusWebView btOgZjbZcAoDIjmO
#define cusWebViewDidStartLoad DUrqhBKwlYyVBIOQ
#define buttonActionToDoSomething TqKkLCPDzugxoOuv
#define addView JzUjFOOutmsRKxah
#define SandMajletIndex AghOHRFTYtzoyyCZ
#define paramString SQJYJkoTkjXkqUXV
#define payPwd FBKBwRRAvpZymzQB
#define defaultPay LahNVOMxohAGFNzg
#define TNOrder HJIMtURGmitplupq
#define initPayMode XbVnpNGoHroESpyP
#define readAuthCode VKuSaloSWdJTlvlR
#define refreshAuthCode jhOETbBoqlrZJmYo
#define oneCodeContentFotmat ekxzCoECWjOgYrlV
#define oneCodeTapShowBigView bglTIhMdsoFnDnWC
#define twoCodeImageScaleBigAnimation FrRGKHrgZrppBgAT
#define buttonAction MogNsMMYeZFigVte
#define changePwdShowState cHSMqgJUaYIKpFff
#define listenNotifier bHSBkEpmDxkTSDyZ
#define textFiledEditChanged fVMIlWuqThzGGSEJ
#define changeBtnBackGround gmSWkjVXOYSXyVqI
#define allInputFields REQNxvXHwSUZnAYz
#define textFieldDidBeginEditing czYUPpcvNnozSROD
#define textFieldShouldReturn QnDgVBwgnIeUntOm
#define setNextResponder NQhfIuCqnyaZbuKL
#define setInputResponderChain rrwoKEMOafqZyJWG
#define dismissKeyboard VDfEXLDvBOCWrMiQ
#define addAuthToolsView QSGHRERmqZUNkkaz
#define shortMsgCodeCountDown MItzAPdCSJRdiPRF
#define refreshTime ilXvyodbDaecYumE
#define shortMsg raWBHOopvySuilIH
#define verificationInput OXZpzYFOeQycaHYw
#define submit FPFIBvagVpaCrqlv
#endif
