#ifndef Demo_codeObfuscation_h
#define Demo_codeObfuscation_h
//confuse string at Tue Oct 24 14:05:22 CST 2017
#define unbandCard EZoWvHbzQZHdLJZD
#define getAuthTools plYLPQSWuzUOaQWg
#define getBankType wNsmxmyRyfeWvDLA
#define changeIconImage pISWpOJkjFLkzHRZ
#define openFastPayTWO kIYSWmjZwmcugheu
#define openFastPay YJZUwIzutrHdVjiD
#define fee qNWCtHGrPqjCDZVV
#define createChildViewControllers enuHPtFmTUrjkvjp
#define setNavigationTheme dxJkWwglzoFQqbhg
#define commitChange rypxffNwMzCzgUOs
#define initMinletsBtn twBQOZDAUrsPHGcw
#define loadData zZpPgbZIuZuzATSP
#define undergroundLogin PQczcZSnhTimGzPP
#define ownPayTools yJUkXyhQepEYRthU
#define setData XjsLtIbTRAlBDvfA
#define exitApplication yjuiVwzxglBLiYAg
#define jsonToString DNgyqwoKQQCGoxXv
#define jsonToDictionary YSFuoAuwiPIAuIkE
#define jsonToArray hgIXoUfvNgInPTyj
#define jsonStringToDictionary gyZIZqKsKyOAVIkP
#define dictionaryToJson njzaXqNQkRFvYdVK
#define jsonStringToArray tgVAiaMMrjoWkEhQ
#define arrayToJSON EdmyMAsMSwJfDOWD
#define passwd eMhrlKYcbCmCcWix
#define limitInfo FsmXTMrzWRZpsIsc
#define limit uRpCfKgewXPtsENI
#define load pnMqtUZzZjAPYJnP
#define settingNavigationBar skvMQYkMKKLlYHAP
#define cusWebView bIQpuvMFowyEavtb
#define cusWebViewDidStartLoad ncgSHwxZyoeUDxRA
#define buttonActionToDoSomething bwIxULZyNIOjKNEV
#define addView XQYKZnyKCDuMXmAb
#define SandMajletIndex wTCwoYsZAfANSsvV
#define paramString kvdfJVHfPSrarfCW
#define payPwd rVLMIEGOwrPEMXtm
#define defaultPay AvhDfhUZiCyzgAwo
#define TNOrder SCDoMiEobVsMofQW
#define initPayMode NiOMZQyfYlMEMYhL
#define readAuthCode eJfipGfavtEfjFJH
#define refreshAuthCode ZUlvfTWRaKYWxpat
#define oneCodeContentFotmat MnqLEULdyNnXBEFZ
#define oneCodeTapShowBigView doWLKALvDostiFfO
#define twoCodeImageScaleBigAnimation cMXQRYfxpSrmukgk
#define buttonAction NVIHQmBQEkKmJgZv
#define changePwdShowState WKllmhkNatDKfHZq
#define listenNotifier WuUYpXaMDpEOFbWQ
#define textFiledEditChanged oRnkeYdJeIJAwSIm
#define changeBtnBackGround mfbAHhIKQvbhqAiQ
#define allInputFields MEmkdBNSwadQvBht
#define textFieldDidBeginEditing bnIhkkslkpOshuES
#define textFieldShouldReturn zUHQEQRjqnhanvPh
#define setNextResponder YGZciievyuAvqlub
#define setInputResponderChain GSvyZLkzDqDRSvAu
#define dismissKeyboard mDgwaIDPwCzGcUji
#define addAuthToolsView aeGhmGotgDBcIUfc
#define shortMsgCodeCountDown YrkruYEXqFdGABde
#define refreshTime SuboymXEReAXHQPR
#define shortMsg uWzvDvntdcrFNLDg
#define verificationInput WOkmseMBQZIcouuJ
#define submit ArhjCgexwBXcFHUX
#endif
