#ifndef Demo_codeObfuscation_h
#define Demo_codeObfuscation_h
//confuse string at Mon Dec 25 15:40:31 CST 2017
#define unbandCard YAuBPUQqiZWuFJDx
#define getAuthTools IVsspTkZQgiGZSSg
#define getBankType PNjAMImnKKdSxoLH
#define changeIconImage KNbuXgVavMlHNiGr
#define openFastPayTWO KBnyQQRGQXVqBGGG
#define openFastPay nPezHTLwkQjFCtcO
#define fee mjWGVkivjuQeoQiH
#define createChildViewControllers AYiwBdBGnjjvxfen
#define setNavigationTheme mApegcNihiNWwtnZ
#define commitChange kFyhwAMmLvxDVSNM
#define initMinletsBtn ixVkEpqDFArZHeJz
#define loadData ZPAkvHnpqNGMipcR
#define undergroundLogin ivKmxvhNltBfxglJ
#define ownPayTools bhPYDWjsGUGGSJVz
#define setData uWjpNEDacilYcoCZ
#define exitApplication jJslUVlUghuCszrp
#define jsonToString LmSifFOqHVINOFko
#define jsonToDictionary nmrXZNoxVAZnAmfn
#define jsonToArray LFskKBhppdyWdjkq
#define jsonStringToDictionary dAxWlwJhpenEhuhi
#define dictionaryToJson NHaOmIeCppzwWJpn
#define jsonStringToArray zbuIgvMWAXjcxddF
#define arrayToJSON tJSzeqRWlKkJKYmU
#define passwd oswqgkKSvpTZHNXf
#define limitInfo jCuEnvQlEJytLWiT
#define limit jzgkyKAlXEQksulL
#define load hmdpAHIpUfxbyXZp
#define settingNavigationBar HJWBWopMRPBCdpAu
#define cusWebView OFpHTpvTDWWRkwwe
#define cusWebViewDidStartLoad MTKtafrNhwpDsVWH
#define buttonActionToDoSomething HymPgdKrPoSwTECe
#define addView ERdoYABLulJbIkfN
#define SandMajletIndex HxXeHtxXsQGKWYTv
#define paramString DdrDQLtfrQQqgxeX
#define payPwd crqdGaCyrBtNmNxj
#define defaultPay wlQZwLKNHStdhTZs
#define TNOrder NDxAJKvnacklkECS
#define initPayMode XZrpwwzzbAUbpskJ
#define readAuthCode JxYtttoAapnzjsCy
#define refreshAuthCode cGmBZjHVmWXFthmQ
#define oneCodeContentFotmat QRMpjDfshPDYfJZW
#define oneCodeTapShowBigView eLIAshqFCgPINTjr
#define twoCodeImageScaleBigAnimation PgOjaxIDJBJtYfWn
#define buttonAction gfjMcBhlgYmCOSNV
#define changePwdShowState BKeSOESKCFioyMmM
#define listenNotifier zfktZeFEiPQwczUQ
#define textFiledEditChanged RSSscYsYkUFmrOjA
#define changeBtnBackGround NGPAKAqzlalxiQOq
#define allInputFields SqhgkwnHZtMzMEzf
#define textFieldDidBeginEditing hRAJjAwGsCEbaANV
#define textFieldShouldReturn kPVdjvupLBhoiseJ
#define setNextResponder OrCfTlcWrcgpeqkd
#define setInputResponderChain shGUvfFWSQRRrdlN
#define dismissKeyboard RlidwqZpJzBiwZfu
#define addAuthToolsView pcLJymDmVQBvhdOb
#define shortMsgCodeCountDown cddhKRbeJjXeijKc
#define refreshTime hIIRLEkqSjJXSfCt
#define shortMsg xpnyzSSYLnqmvenc
#define verificationInput DKTeKVzWNnvLFnuk
#define submit UaDaZuZnhhfIJqot
#endif
