platform :ios, ‘7.0’
#use_frameworks!个别需要用到它，比如reactiveCocoa

target 'sandbao' do
  	pod 'SDWebImage', '~> 4.0'
  	pod "pop"
  	pod 'Masonry'
  	pod 'IQKeyboardManager'
	pod 'RESideMenu', '~> 4.0.7'
	pod 'UMengAnalytics-NO-IDFA'

end
