platform :ios, ‘8.0’
#use_frameworks!个别需要用到它，比如reactiveCocoa

target 'sandbao' do
pod 'SDWebImage', '~> 4.0’
pod 'WechatOpenSDK'
pod "pop"
pod 'Masonry'
pod 'IQKeyboardManager', '~> 5.0.6'
pod 'RESideMenu', '~> 4.0.7'
pod 'UMengAnalytics-NO-IDFA'
pod 'MQTTClient'

pod 'Pgyer'
pod 'PgyUpdate'

end
