#ifndef Demo_codeObfuscation_h
#define Demo_codeObfuscation_h
//confuse string at Thu Feb  8 14:49:18 CST 2018
#define unbandCard iaOiXztXnnJvRghC
#define getAuthTools oKEsfGzpLBSPagvg
#define getBankType wBFMeaZmrQFnpiHL
#define changeIconImage YADdVOyqXWonIcYX
#define openFastPayTWO tyrtcPQSWrJWfEDb
#define openFastPay QHrfrYTJLEiHiwOi
#define fee LWsTaZjTUGVkEFfb
#define createChildViewControllers iDyCLLCfPKNlZFRo
#define setNavigationTheme nVKxYWocHBGzBUxC
#define commitChange AsZyVoOAGGJnRsVj
#define initMinletsBtn EbHEtiVswlIOvkoP
#define loadData bltLCQSjNMWkvUMy
#define undergroundLogin MxUyTyhsGXZbpYzP
#define ownPayTools ryaOfkLbyqObxevf
#define setData AklhjrOJUyKsbmNF
#define exitApplication NeEgLhsGahSCoOcX
#define jsonToString HHevkBNtotRWFWQK
#define jsonToDictionary gtSvWWaAZOGSKGnR
#define jsonToArray vAQtPlzXMKQDLtoN
#define jsonStringToDictionary RWhKGeUHwZaHoRIk
#define dictionaryToJson brMbFhleEaFfBycV
#define jsonStringToArray IufxduiTFaOrKjYV
#define arrayToJSON XVeiavSmwHUBrAsz
#define passwd BuoCjbBGjBZbBnnM
#define limitInfo pORMHdaohCOKZsAi
#define limit QGqdKugFoFirKBLE
#define load YxKyLhuuRDnaMRfa
#define settingNavigationBar kKOiPPZVPEtEIhMq
#define cusWebView VZRtHuocQvmHunqN
#define cusWebViewDidStartLoad BWwNhRKfphsiHIwB
#define buttonActionToDoSomething GMsgCoBRseUdjvhj
#define addView vYDJtMEtZtkQsKhm
#define SandMajletIndex BgwpZthMuOAMUQkH
#define paramString WrTPBVQViVBpHcuT
#define payPwd ZTznzpulrZdKjubp
#define defaultPay vgLbPABHhojeGsFz
#define TNOrder aKPBmmTrZhacLsax
#define initPayMode TxDmPlffABulXhMl
#define readAuthCode aRnvphmaWaxbIoBL
#define refreshAuthCode KcAzfAfVaVdABmnn
#define oneCodeContentFotmat fclByUHxyfOpFIyV
#define oneCodeTapShowBigView CwsvSsBZcbBKfglx
#define twoCodeImageScaleBigAnimation WOBzfwozSzofdpeX
#define buttonAction vommgIehHdroHQZC
#define changePwdShowState QXExYhKOSnMEInSP
#define listenNotifier dXkKkpEAQhFfJVzS
#define textFiledEditChanged IjOUfRFbOsLrCzGO
#define changeBtnBackGround ZVkalmjDILVMUWlg
#define allInputFields ZjXkZEMIKoSAbnko
#define textFieldDidBeginEditing ugCrjksfkqSonSsK
#define textFieldShouldReturn DOdifJsTAWwuLlnf
#define setNextResponder rJpQOXdSfmLkHFHO
#define setInputResponderChain GeNVjCPtoOWGRuAu
#define dismissKeyboard KOMabostWtEjQJFE
#define addAuthToolsView DFVhrZdHiUxczqUa
#define shortMsgCodeCountDown pInxjkltuEYGMOmK
#define refreshTime GgNSdjEnbHQKslRU
#define shortMsg MofLishICgSbugGF
#define verificationInput xgdvInQfIYyIOsHl
#define submit SJVyOSGDteozhftf
#endif
