#ifndef Demo_codeObfuscation_h
#define Demo_codeObfuscation_h
//confuse string at Wed Oct 18 22:23:27 CST 2017
#define unbandCard NyvToUeRJtzYmacF
#define getAuthTools MLJedEklaWtBbHLi
#define getBankType oOfGTCqWTZsRHUPT
#define changeIconImage pZRTSGCDebEVbieR
#define openFastPayTWO uOiKIMnySeDgzPFG
#define openFastPay zNkPMRvpgmmEpmLF
#define fee aNlHRCMkYoIYeIie
#define createChildViewControllers gOgPtGLGqiYAvAxt
#define setNavigationTheme vmftaSDCEhePVvsW
#define commitChange wrwWPayFrUrAGZYp
#define initMinletsBtn tDgMPOsurEmZxIfU
#define loadData jJbDatfBuyquqNbr
#define undergroundLogin ifZNWYKbMFwsDkXd
#define ownPayTools CPBwqxomrYrTtpzA
#define setData PridTVBSGcaYfUUU
#define exitApplication HGxJvDnnEzzclPOZ
#define jsonToString ZHzJAzIfQjmMPnfi
#define jsonToDictionary MHAbKgONXRRDfMBh
#define jsonToArray oAqHmWVhAWHzZvUT
#define jsonStringToDictionary HmHUcfXIFFrdejqG
#define dictionaryToJson QClpVrjdMlBYlQNZ
#define jsonStringToArray hTiixAZBVyNvBpMk
#define arrayToJSON VBmXFFrorSGrjiLB
#define passwd ReeQmLEZeNbtdIay
#define limitInfo aUabBdMGtvHWDUsv
#define limit CGkrchORNvNCfRBb
#define load iawPHalvdADhTABy
#define settingNavigationBar jJtSzvVxieNiBjgA
#define cusWebView BAxjzevseHlmbjBs
#define cusWebViewDidStartLoad zasbTlREnWYCKPmc
#define buttonActionToDoSomething kpzYpjqiLqsJOEOD
#define addView zXnNvjtToTuONwSS
#define SandMajletIndex noNebSVqPLqecupj
#define paramString iOxJXXluMpPHsayu
#define payPwd SLHbGlpncaJEcdDX
#define defaultPay NcEXiGXDapDwuNgl
#define TNOrder syIVGAyjKCRWSCcY
#define initPayMode AuElifuvFSRpQcRG
#define readAuthCode AmisNRYLvrpHOxIH
#define refreshAuthCode PnNZTmwJnltBNlid
#define oneCodeContentFotmat pPxFnqdTbihutNlf
#define oneCodeTapShowBigView jbcdMEWkbLUfnLED
#define twoCodeImageScaleBigAnimation XjuLGEqJdRTJCBLi
#define buttonAction NSZIyQuqKnKPkIFL
#define changePwdShowState ypMzitJrueoJdKdg
#define listenNotifier zvLlvJULVpWPjMCv
#define textFiledEditChanged qtYyddwzlJEkNbQz
#define changeBtnBackGround lmfrvauCFselEoJG
#define allInputFields pjLRQdYqRXsJknRR
#define textFieldDidBeginEditing QYepdOTNienLGtCa
#define textFieldShouldReturn jGIdSZDfJIycopTw
#define setNextResponder OIsRUBWTnESvcheg
#define setInputResponderChain UxsIKKCxHyLbPotx
#define dismissKeyboard sPKdKoOFQXimUYpy
#define addAuthToolsView GssbncdCInLSmgKW
#define shortMsgCodeCountDown kXIsPMcgMRdXIkex
#define refreshTime ZtCGFUVuynSOddUq
#define shortMsg XmjNIGuwbLHiYale
#define verificationInput DXmJKKwXpmuXciSq
#define submit focnMUSrYssfiSqe
#endif
