#ifndef Demo_codeObfuscation_h
#define Demo_codeObfuscation_h
//confuse string at Mon Oct 16 18:11:13 CST 2017
#define unbandCard ZhvONXYnLQjsHhVS
#define getAuthTools fRXYLPEZwENyMvsV
#define getBankType ORPjGjGYtXJrWeqI
#define changeIconImage nngCOTjXarbBmGWy
#define openFastPayTWO ZmiayyOioTSIqiaj
#define openFastPay ZjmvGGllMqNztnYc
#define fee FfneYnaxcrfWLcnp
#define createChildViewControllers kkMcdkPqfgNbIMZu
#define setNavigationTheme DBiJEtKGgEzqYSvS
#define commitChange SeNuiAqQLJNMhWkt
#define initMinletsBtn yUZKcGZRsfiBpMoJ
#define loadData bIjWOKRFBEwocjrY
#define undergroundLogin CIhIMcPKlvoYHiOO
#define ownPayTools XBOpZuGpFnjOnBIF
#define setData JvCAsOaAYsQmBEth
#define exitApplication dJYgUXywRqBWlKQD
#define jsonToString OnLzcTaoNFHDgGxD
#define jsonToDictionary CXkebXCXUYIHkmoL
#define jsonToArray sLaCcZgXvXzCzsUd
#define jsonStringToDictionary vfPqOsVOpbydiasj
#define dictionaryToJson RAznbFjJMoyBaNHA
#define jsonStringToArray LtSbwjvwrRNnQkuo
#define arrayToJSON AaaHYXstCiLSZlWW
#define passwd INZAlgeyzbtLWpoG
#define limitInfo ClmMDnxeupLNHsQS
#define limit hQlKShGQKNlAQJau
#define load KTgJUAMzDROLRHTw
#define settingNavigationBar lJQWHtlLVodBowcA
#define cusWebView BiduLwlWznswzbid
#define cusWebViewDidStartLoad rkXREkDjxceJyIsj
#define buttonActionToDoSomething UYxBfUZbCxFHCqQt
#define addView GkNwAOWaajpASbkm
#define SandMajletIndex aOwCpTjRDgtAZQJK
#define paramString uIZPyJWVtxfCwMQa
#define payPwd FbHnFaNCTZRAEwhi
#define defaultPay BjFhWdkOqdYoeqNT
#define TNOrder RUQKBrZOfyxnJevS
#define initPayMode FfafROkwILzZfFrs
#define readAuthCode qglKrzNSvBcKWdid
#define refreshAuthCode YKyyiYPMhvqInsdK
#define oneCodeContentFotmat xZWzMspCYilMTHDv
#define oneCodeTapShowBigView pmsdiRDHiLgGDCDF
#define twoCodeImageScaleBigAnimation JgVsZhbzuDrGWgOm
#define buttonAction DYnBQYmEHbPkQVnc
#define changePwdShowState athVHFLsPrhGYEOd
#define listenNotifier qIXRSxwoRhBzCKzv
#define textFiledEditChanged YNANrZQYtztSzIHc
#define changeBtnBackGround uzbefmUzEAgbEOrb
#define allInputFields aJICAgHYnsoRmaLe
#define textFieldDidBeginEditing cRNpjaDQQrqzVbqs
#define textFieldShouldReturn tcpPSOpxhVYbFpfa
#define setNextResponder kqUweUcmdNHhzBcb
#define setInputResponderChain JNJHJvjdnkeiLnDx
#define dismissKeyboard uMmUIDktqeJvoKnD
#define addAuthToolsView LYtAzDMVzHHKVlXq
#define shortMsgCodeCountDown LHcAlGfgHuBnhAUU
#define refreshTime elyBSdDfWitFAnDg
#define shortMsg TktJXFqsXQAUqIxh
#define verificationInput ixtJItdqBeZcfkTa
#define submit xCjqEiyRoXDQkgFS
#endif
