#ifndef Demo_codeObfuscation_h
#define Demo_codeObfuscation_h
//confuse string at Thu Nov 16 15:15:48 CST 2017
#define unbandCard nGRORyIRkuXKUbKN
#define getAuthTools OscMHyYHEkEPwoND
#define getBankType whBTRYXvqaFoQLIz
#define changeIconImage rbaMGKqenSuUCjJG
#define openFastPayTWO SNxQaezJvJEsQkPx
#define openFastPay txQnSHmFqxuWBGYl
#define fee WQTRVexHdNlPZTYQ
#define createChildViewControllers iNgREYwdqBRniOIO
#define setNavigationTheme GkjVYSXSnQTYCJpl
#define commitChange HKRdeTcjdTKMYijY
#define initMinletsBtn ZThLEudXOfNaJPHK
#define loadData EztjLYmiuFoIBmKy
#define undergroundLogin veIDVhbienyhnTvm
#define ownPayTools WCqZxykpOdBdatiM
#define setData DyoniPkVASIBqbPc
#define exitApplication fRuuNpTBLpmNMGUe
#define jsonToString jbHzPZHUfOLfHQcn
#define jsonToDictionary tnZZdYUVcGIBZjVu
#define jsonToArray CVxUwlMtjLnocsVh
#define jsonStringToDictionary wEDZSwbymRoXDVwa
#define dictionaryToJson gqUFykjxYPTywslN
#define jsonStringToArray cSROXXikCoktTxxL
#define arrayToJSON vzvOnDFLOUNlYwJw
#define passwd grposjnwVYucpqEi
#define limitInfo gNAMvTYNEsYmMRck
#define limit aWpVMwMAHKPbVbHJ
#define load IixdfqLWdhNacfbd
#define settingNavigationBar fLjHXXFslRuxCxik
#define cusWebView LtSldhkdWGfSxJIn
#define cusWebViewDidStartLoad nhtmXxaEMFCFGsTK
#define buttonActionToDoSomething PmXVRkcXEJdMswSR
#define addView RNypwXflshhMyoKg
#define SandMajletIndex iGTJXYvfjyhptBOT
#define paramString QvZpNJFFVzvZyVjh
#define payPwd JLvlSNiZXIjImkoB
#define defaultPay XrWJcElvuXiHBQJa
#define TNOrder bnYtwoYQdpwJfqCo
#define initPayMode IfxkeHuFdglENYrd
#define readAuthCode FuNbYGGRiHcnqmPe
#define refreshAuthCode LpbAaFCgmUYTUgYX
#define oneCodeContentFotmat uiqxiezoxSLaSOkI
#define oneCodeTapShowBigView TqJvRfAgkYUnfBRk
#define twoCodeImageScaleBigAnimation kjXkSPKTXJnDqDiC
#define buttonAction ReETIryoHtprLKcA
#define changePwdShowState WRdkDfsOlUWOzWRL
#define listenNotifier JzUVZxiekhaqNkIa
#define textFiledEditChanged kMcxDrQyBmHUcDrS
#define changeBtnBackGround ssaADPneCGOfuinS
#define allInputFields cvDYSuMZKKfzqdnb
#define textFieldDidBeginEditing bbgoqMyTVyKrAcuI
#define textFieldShouldReturn cdGAUDFzdEXNvNTf
#define setNextResponder ZfvzhvAWWFTAkHLx
#define setInputResponderChain UgBXZEuJCVMLgipT
#define dismissKeyboard HYZYJIAKevsjDKrD
#define addAuthToolsView UMLGJsLTDfdYouiD
#define shortMsgCodeCountDown LguHbKrUBqqTVTUZ
#define refreshTime XgOODNZrnavLfMEF
#define shortMsg MaEQlzAXyVTesTNq
#define verificationInput nBklgbPpVauKSefH
#define submit yhUJSInGxCdIBqnQ
#endif
